name: Deploy to AWS Lambda
# ci test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Lambda Layer (Docker)
        run: |
          docker build -t lambda-layer-builder infrastructure/lambda_base_layer/
          container_id=$(docker create lambda-layer-builder)
          docker cp $container_id:/layer.zip infrastructure/lambda_base_layer/layer.zip
          docker rm $container_id

      - name: Install CDK dependencies
        working-directory: infrastructure
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy with CDK
        working-directory: infrastructure
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx cdk deploy --require-approval never
